"""initial schema

Revision ID: 63e42fa584ae
Revises: 
Create Date: 2026-04-12 15:29:08.913832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e42fa584ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fechamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_entrada', sa.Float(), nullable=False),
    sa.Column('total_saida', sa.Float(), nullable=False),
    sa.Column('saldo_esperado', sa.Float(), nullable=False),
    sa.Column('saldo_informado', sa.Float(), nullable=False),
    sa.Column('diferenca', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacao')
    op.drop_table('fechamento')
    # ### end Alembic commands ###
